In [28]:
import pandas as pd
df = pd.read_csv("IRIS.csv")

In [29]:
df.head(10)
df.shape
df.dtypes
df.head(2)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa

In [30]:
df[(df['petal_length']>4.5) & (df['species'] == 'Iris-virginica')]

df.groupby('species').agg(
    Avg_sepal_length =("sepal_length","mean"),
    Max_petal_width = ("petal_width","max"),
    Std_sepal_width = ("sepal_width","std")
)

                 Avg_sepal_length  Max_petal_width  Std_sepal_width
species
Iris-setosa                 5.006              0.6         0.381024
Iris-versicolor             5.936              1.8         0.313798
Iris-virginica              6.588              2.5         0.322497

In [33]:
df = df.assign(petal_ratio = df['petal_length']/df['petal_width'])

df.groupby('species')['petal_ratio'].mean()

species
Iris-setosa        7.078000
Iris-versicolor    3.242837
Iris-virginica     2.780662
Name: petal_ratio, dtype: float64

In [37]:
df1 = pd.read_csv("Titanic-Dataset.csv")
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [55]:
df1[["Name","Sex","Age","Fare","Survived"]]

df1[(df1['Sex'] == 'female') & (df1['Fare']>30)]

df1.groupby('Pclass').agg(
    Survival_Rate =("Survived",(lambda x: x.mean()*100)),
    Average_Fare = ("Fare","mean"),
    Average_Age =("Age","mean")
)

        Survival_Rate  Average_Fare  Average_Age
Pclass
1           62.962963     84.154687    38.233441
2           47.282609     20.662183    29.877630
3           24.236253     13.675550    25.140620